package:
  name: sensorml2iso
  version: {{ GIT_DESCRIBE_TAG|replace("v","") }}

source:
  path: ../

build:
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - sensorml2iso = sensorml2iso.command_line:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - owslib
    - geopandas
    - jinja2
    - lxml
    - numpy
    - pandas
    - pyoos >=0.8.3
    - shapely

test:
  requires:
    - pytest
  imports:
    - sensorml2iso
  commands:
    - sensorml2iso -h
    - sensorml2iso -s http://data.nanoos.org/52nsos/sos/kvp
    - py.test -s -rxs -v sensorml2iso

about:
  home: https://github.com/ioos/sensorml2iso
  license: MIT
  license_file: LICENSE
  summary: 'Query an IOOS SOS service for active sensors and output ISO 19115-2-compliant xml.'

extra:
  recipe-maintainers:
    - mwengren
    - ocefpaf
